Prism.languages.perl6 = {
  'number': /\b(?:0o[0-7](?:_?[0-7])*|0x[a-fA-F0-9](?:_?[a-fA-F0-9])*|(?:(:?[0-9](?:_?[0-9])*)?\.)?[0-9](?:_?[0-9])*(?:e-?[0-9](?:_?[0-9])*)?)i?\b/,
  'type': /\b(?:AST|Any|Block|Bool|CallFrame|Callable|Code|Complex(?:Str)?|Cool|Date(?:Time|ish)?|Duration|FatRat|HyperWhatever|Instant|Int(?:Str)?|Junction|Label|Macro|Method|Mu|Nil|Num(?:Str|eric)?|ObjAt|Parameter|Proxy|Rat(?:Str|ional)?|Real|Routine|Scalar|Signature|Str(?:ingy)?|Sub(?:method)?|ValueObjAt|Variable|Version|Whatever(?:Code)?|atomicint|Array|Associative|Bag(?:Hash|gy)?|Blob|Buf|Capture|Enumeration|Hash|Iterable|Iterator|List|Map|Mix(?:Hash|y)?|NFC|NFD|NFKC|NFKD|Pair|Positional(?:BindFailover)?|PseudoStash|QuantHash|Range|Seq|Set(?:Hash|ty)?|Slip|Stash|Uni|Attribute|Cancellation|Channel|CurrentThreadScheduler|Cursor|Distro|Grammar|IO(?:::(ArgFiles|(?:Cat)?Handle|Notification|Path(?:::(?:Cygwin|QNX|Unix|Win32))?|Pipe|Socket(?:::(?:Async|INET))?|Spec(?:::(?:Cygwin|QNX|Unix|Win32)|ial)?))?|Kernel|Lock|Match|Order|Pod::(?:Block(?:::(Code|Comment|Declarator|Named|Para|Table))?|Heading|Item)|Proc(?:::Async)?|Promise|Regex|Scheduler|Semaphore|Supplier(?:::Preserving)?|Supply|Tap|Thread(?:PoolScheduler)?|VM|Backtrace(?:::Frame)?|Exception|Failure|X::(?:AdHoc|Anon::(?:Augment|Multi)|Assignment::RO|Attribute::(?:(?:No)?Package|Undeclared)|Augment::NoSuchType|Bind(?:::(?:NativeType|Slice))?|Caller::NotDynamic|Channel::(?:Receive|Send)OnClosed|Comp(?:osition::NotComposable)?|Constructor::Positional|ControlFlow(?:::Return)?|DateTime::TimezoneClash|Declaration::Scope(?:::Multi)?|Does::TypeObject|Eval::NoSuchLang|Export::NameClash|IO(?:::(?:Ch(?:dir|mod)|Copy|Cwd|Dir|DoesNotExist|Link|(?:Mk|Rm)dir|Move|Rename|(?:Sym|Un)link))?|Inheritance::(?:NotComposed|Unsupported)|Method::(?:InvalidQualifier|NotFound|Private::(?:Permission|Unqualified))|Mixin::NotComposable|NYI|NoDispatcher|Numeric::Real|OS|Obsolete|OutOfRange|Package::Stubbed|Parameter::(?:Default|MultipleTypeConstraints)|Parameter::(?:Placeholder|Twigil|WrongOrder)|Phaser::(?:Multiple|PrePost)|Placeholder::(?:Block|Mainline)|Pod|Proc::(?:Async(?:::(?:AlreadyStarted|CharsOrBytes|MustBeStarted|OpenForWriting|TapBeforeSpawn))?|Unsuccessful)|Promise::(?:CauseOnlyValidOnBroken|Vowed)|Redeclaration|Role::Initialization|Seq::Consumed|Sequence::Deduction|Signature::(?:NameClash|Placeholder)|Str::Numeric|StubCode|Syntax(?:::(?:Augment::WithoutMonkeyTyping|Comment::Embedded|Confused|InfixInTermPosition|Malformed|Missing|NegatedPair|NoSelf|Number::RadixOutOfRange|P5|Regex::(?:Adverb|SolitaryQuantifier)|Reserved|Self::WithoutObject|Signature::InvocantMarker|Term::MissingInitializer|UnlessElse|Variable::(?:Match|Numeric|Twigil))?)?|Temporal(?:::InvalidFormat)?|TypeCheck(?:::(?:Assignment|Binding|Return|Splice))?|Undeclared)?)(?::[DU_])?(?!['-]\b)/,
	'operator': [
    {
      // whitespace/metaoperator required before operators beginning with <
      pattern: /(?:(\s)|(?:\b[RSXZ]+))(?:<(?:<?==|=>?|<)?)/,
      lookbehind: true
    },
    /(?:(?:\b[RSXZ]+)?(?:(?:(?:\^|\b)fff?(?:\^|(?!['-])\b))|\((?:[&+-.^|]|[<>]=?|cont|elem)\)|\*\*?|==>>?|[«»∈∉∋∌∖∘∩∪≠≤≥⊂⊃⊄⊅⊆⊇⊈⊉⊍⊎⊖]|⚛(?:\+[+=]?|-[-=]?|−?=)?|>[>=]?|\+(?:[&<>^|]|\+⚛?)?|-(?:-⚛?)?|\/\/?|=(?:(?:==?)|[:~]=|>)|\?(?:(?:\?\??)|[|^])?|!(?:(?:!!?)|=)?|%%?|&&?|\.{3}\^?|\^?\.{2}\^?|\.[&*+=?^]?|…\^?|\^\^?|\|\|?|,|:(?::?=)?|~[&<>^|~]?))|(?:\b[RSXZ]*(?:before|after|xor|or(?:else)?|(?:not)?and(?:then)?|min(?:max)?|max|so|not|xx?|div|mod|gcd|lcm|temp|let|does|but|(?:uni)?cmp|leg|eqv?|ne|[gl][te]|Z|X)(?!['-])\b)/
  ]
};
